---
title: "STAT 407 Homework 2"
author: "Charles Hwang"
date: "10/8/2021"
output: pdf_document
---
## Problem 4.3
```{r Problem 4.3, message=FALSE}
rm(list=ls())
A<-c(73,68,74,71,67)
B<-c(73,67,75,72,70)
C<-c(75,68,78,73,68)
D<-c(73,71,75,75,69)
strength<-c(A,B,C,D)
blbolt<-as.factor(rep(1:5,times=4))
trchem<-as.factor(rep(1:4,each=5))
par(mfrow=c(1,2))
boxplot(strength~blbolt,xlab="blocks")
boxplot(strength~trchem,xlab="treatments")
t<-lm(strength~trchem+blbolt)
library(car)
anova(t)
# We fail to reject the null hypothesis at the alpha = 0.05 level. There is insufficient
# evidence (p = 0.1211) that the mean tensile strengths of the chemical agents are different.
bartlett.test(strength~trchem) # Testing normality and equal variance assumptions
bartlett.test(strength~blbolt)
bartlett.test(t$residuals~trchem)
leveneTest(strength~trchem)
shapiro.test(t$residual)
# We should exercise caution here because the null hypothesis for the Shapiro-Wilk test is
# rejected (p = 0.04054) and the residuals may not be normally distributed.
par(mfrow=c(2,2)) 
qqnorm(t$residuals)
qqline(t$residuals)
plot(c(trchem),t$residuals)  
abline(h=0)
plot(c(blbolt),t$residuals)
abline(h=0)
plot(t$fitted.values,t$residuals)
abline(h=0)
# There does not appear to be any pattern in the Q-Q plot or residual plots.
```

## Problem 4.8
(a)
```{r Problem 4.8(a)}
NE<-c(250,400,275)
NW<-c(350,525,340)
SE<-c(219,390,200)
SW<-c(375,580,310)
response<-as.vector(rbind(NE,NW,SE,SW))
blregion<-as.factor(rep(1:4,times=3))
trdesign<-as.factor(rep(1:3,each=4))
par(mfrow=c(1,2))
boxplot(response~blregion,xlab="blocks")
boxplot(response~trdesign,xlab="treatments")
r<-lm(response~trdesign+blregion)
anova(r)
# We reject the null hypothesis at the alpha = 0.05 level. There is sufficient 
# evidence (p = 0.0002) that the mean response rate of at least one mailer is different.
bartlett.test(response~trdesign) # Testing normality and equal variance assumptions
bartlett.test(response~blregion)
leveneTest(response~trdesign)
```

(b)
```{r Problem 4.8(b)}
library(agricolae)
LSDr<-LSD.test(aov(response~trdesign+blregion),"trdesign")
LSDr
```

We can see that design 2 clearly has a different mean response rate than designs 1 and 3.

(c)
```{r Problem 4.8(c)}
bartlett.test(r$residuals~trdesign)
# We should exercise caution here because the null hypothesis for the Bartlett's test
# is rejected (p = 0.04383) and the residuals may not have equal variance.
shapiro.test(r$residual)
par(mfrow=c(2,2))
qqnorm(r$residuals)
qqline(r$residuals)
plot(c(trdesign),r$residuals)  
abline(h=0)
plot(c(blregion),r$residuals)
abline(h=0)
plot(r$fitted.values,r$residuals)
abline(h=0)
# There is some variation in the Q-Q plot, but there does not appear to be any pattern
# in the residual plots.
friedman.test(response,trdesign,blregion) # Additional post-hoc analysis
TukeyHSD(aov(response~trdesign+blregion),conf.level=0.95)$trdesign
```

## Problem 4.9
(a)
```{r Problem 4.9(a)}
X<-c(0.500,0.634,0.487,0.329,0.512)
Y<-c(0.535,0.675,0.520,0.435,0.540)
Z<-c(0.513,0.595,0.488,0.400,0.510)
economy<-c(X,Y,Z)
bltruck<-as.factor(rep(1:5,times=3))
troil<-as.factor(rep(1:3,each=5))
par(mfrow=c(1,2))
boxplot(economy~bltruck,xlab="blocks")
boxplot(economy~troil,xlab="treatments")
e<-lm(economy~troil+bltruck)
anova(e)
# We reject the null hypothesis at the alpha = 0.05 level. There is sufficient
# evidence (p = 0.0223) that the mean fuel economy of at least one oil is different.
bartlett.test(economy~troil) # Testing normality and equal variance assumptions
bartlett.test(economy~bltruck)
leveneTest(economy~troil)
```

(b)
```{r Problem 4.9(b)}
LSDe<-LSD.test(aov(economy~troil+bltruck),"troil")
LSDe
```

We can see that oil 2 has a different mean fuel economy than oils 1 and 3.

(c)
```{r Problem 4.9(c)}
bartlett.test(e$residuals~troil)
shapiro.test(e$residual)
# None of the null hypotheses were rejected, so the normality and
par(mfrow=c(2,2))  # equal variance assumptions appear to be met.
qqnorm(e$residuals)
qqline(e$residuals)
plot(c(troil),e$residuals)  
abline(h=0)
plot(c(bltruck),e$residuals)
abline(h=0)
plot(e$fitted.values,e$residuals)
abline(h=0)
# There does not appear to be any pattern in the Q-Q plot or residual plots.
friedman.test(economy,troil,bltruck) # Additional post-hoc analysis
TukeyHSD(aov(economy~troil+bltruck),conf.level=0.95)$troil
```

## Problem 4.21
```{r Problem 4.21}
fou<-c(10,6,6,6,6)
six<-c(7,6,6,1,6)
eig<-c(5,3,3,2,5)
ten<-c(6,4,4,2,3)
time<-c(fou,six,eig,ten)
blsubj<-as.factor(rep(1:5,times=4))
trdist<-as.factor(rep(1:4,each=5))
par(mfrow=c(1,2))
boxplot(time~blsubj,xlab="blocks")
boxplot(time~trdist,xlab="treatments")
ft<-lm(time~trdist+blsubj)
anova(ft)
# We reject the null hypothesis at the alpha = 0.05 level. There is sufficient
# evidence (p = 0.0025) that the mean focus time for at least one distance is different.
bartlett.test(time~trdist) # Testing normality and equal variance assumptions
bartlett.test(time~blsubj)
bartlett.test(ft$residuals~trdist)
leveneTest(time~trdist)
shapiro.test(ft$residual)
# None of the null hypotheses were rejected, so the normality and
par(mfrow=c(2,2))  # equal variance assumptions appear to be met.
qqnorm(ft$residuals)
qqline(ft$residuals)
plot(c(trdist),ft$residuals)  
abline(h=0)
plot(c(blsubj),ft$residuals)
abline(h=0)
plot(ft$fitted.values,ft$residuals)
abline(h=0)
# There does not appear to be any pattern in the Q-Q plot. There appears to be some
# pattern in the residuals vs. fitted values plot, but remember that the sample sizes
# for each distance are relatively small.
friedman.test(time,trdist,blsubj) # Post-hoc analysis
LSDft<-LSD.test(aov(time~trdist+blsubj),"trdist")
LSDft
TukeyHSD(aov(time~trdist+blsubj),conf.level=0.95)$trdist
```

## Problem 4.22
```{r Problem 4.22}
reaction<-c(8,7,1,7,3,11,2,7,3,8,4,9,10,1,5,6,8,6,6,10,4,2,3,8,8)
day<-as.factor(rep(1:5,times=5))
batch<-as.factor(rep(1:5,each=5))
ing<-c("A","B","D","C","E","C","E","A","D","B","B","A","C","E","D","D","C","E","B","A","E","D","B","A","C")
par(mfrow=c(1,3))
boxplot(reaction~ing)
boxplot(reaction~day,xlab="blocks")
boxplot(reaction~batch,xlab="treatments")
rt<-lm(reaction~ing+day+batch)
anova(rt)
# We reject the null hypothesis at the alpha = 0.05 level. There is sufficient
# evidence (p = 0.0005) that the mean reaction time for at least one ingredient is different.
bartlett.test(reaction~ing) # Testing normality and equal variance assumptions
bartlett.test(reaction~batch)
bartlett.test(reaction~day)
bartlett.test(rt$residuals~batch)
f<-vector() # Levene's test
for(j in c("A","B","C","D")) f[ing==j]<-abs(reaction[ing==j]-median(reaction[ing==j]))
lt<-lm(f~ing)
anova(lt)
shapiro.test(rt$residual)
# None of the null hypotheses were rejected, so the normality and
par(mfrow=c(2,2))  # equal variance assumptions appear to be met.
qqnorm(rt$residuals)
qqline(rt$residuals)
plot(c(batch),rt$residuals)  
abline(h=0)
plot(c(day),rt$residuals)
abline(h=0)
plot(rt$fitted.values,rt$residuals)
abline(h=0)
# There is some variation in the Q-Q plot, but there does not appear to be any pattern
# in the residual plots.
LSDlt<-LSD.test(aov(reaction~ing+day+batch),"ing") # Post-hoc analysis
LSDlt
TukeyHSD(aov(reaction~ing+day+batch),conf.level=0.95)$ing
```

## Problem 4.27
```{r Problem 4.27, message=FALSE}
SLIM<-c(1244,21,82,2221,905,839)
COCOMOA<-c(281,129,396,1306,336,910)
COCOMOR<-c(220,84,458,543,300,794)
COCONOC<-c(225,83,425,552,291,826)
FUNCTIONPOINTS<-c(19,11,-34,121,15,103)
ESTIMALS<-c(-20,35,-53,170,104,199)
accuracy<-c(SLIM,COCOMOA,COCOMOR,COCONOC,FUNCTIONPOINTS,ESTIMALS)
blproj<-as.factor(rep(1:6,times=6))
tralgo<-as.factor(rep(1:6,each=6))
anova(lm(accuracy~tralgo+blproj))
library(dplyr) # Using Equation 4.16: var_blocks=(MSB-MSE)/a on page 152
(anova(lm(accuracy~tralgo+blproj))$"Mean Sq"[2]-anova(lm(accuracy~tralgo+blproj))$"Mean Sq"[3])/n_distinct(blproj)
```