---
title: "Personal Key Indicators of Heart Disease Project Code"
author: "Charles Hwang"
date: "12/18/2022"
output: pdf_document
---
Charles Hwang

Dr. Xi

STAT 408-001

2022 December 18

## Data

```{r Data}
rm(list=ls())
heart<-read.csv("~/Desktop/Notes/Graduate/STAT 408 - Applied Regression Analysis/heart_2020_cleaned.csv")
heart$HeartDisease<-as.factor(heart$HeartDisease)
heart$Smoking<-as.factor(heart$Smoking)
heart$AlcoholDrinking<-as.factor(heart$AlcoholDrinking)
heart$Stroke<-as.factor(heart$Stroke)
heart$DiffWalking<-as.factor(heart$DiffWalking)
heart$Sex<-as.factor(heart$Sex)
heart$AgeCategory<-as.factor(heart$AgeCategory)
heart$Race<-as.factor(heart$Race)
heart$Diabetic<-factor(heart$Diabetic,labels=c("No","BL","Yes","YesPreg")) # Renaming levels
heart$PhysicalActivity<-as.factor(heart$PhysicalActivity)
heart$GenHealth<-factor(heart$GenHealth,labels=c(5,2,3,1,4)) # Reordering levels to EX, VG, G, F, P
heart$Asthma<-as.factor(heart$Asthma)
heart$KidneyDisease<-as.factor(heart$KidneyDisease)
heart$SkinCancer<-as.factor(heart$SkinCancer)
set.seed(612)
s<-sort(sample(nrow(heart),round(nrow(heart)*.8)))
train<-heart[s,]
test<-heart[-s,]
rm(s)
table(heart$HeartDisease) # p
```

## Data Visualization

```{r Data Visualization}
boxplot(heart$BMI,main="Body Mass Index (BMI)",horizontal=TRUE)
abline(v=c(18.5,25,30,35,40),lty="17") # Underweight, normal, overweight, class I-III obesity
boxplot(heart$MentalHealth,heart$PhysicalHealth,heart$SleepTime,names=c("Poor MH","Poor PH","Sleep"),main="# of Poor Mental/Physical Health Days (Last 30) and Average Sleep",xaxp=c(0,30,15),horizontal=TRUE)
cor(heart[,c("BMI","PhysicalHealth","MentalHealth","SleepTime")])
```

## Model

```{r Model}
summary(glm(HeartDisease~.,family=binomial,data=train))
step(glm(HeartDisease~.,family=binomial,data=train),direction="both") # Same as full model
table(train[train$AgeCategory=="25-29","HeartDisease"]) # Non-significant levels/variables
table(train[train$Diabetic=="YesPreg","HeartDisease"])
table(train[train$Race=="Other","HeartDisease"])
table(train$PhysicalActivity,train$HeartDisease)
summary(glm(HeartDisease~.,family=binomial,data=train))$aic # Akaike information criterion (AIC)
pred<-predict(glm(HeartDisease~.,family=binomial,data=train),test,type="response")
table(round(pred))                # Predictions
table(test$HeartDisease)          # Actual values
glmt<-table(test$HeartDisease,round(pred))
glmt                              # Confusion matrix
sum(diag(glmt))/nrow(test)        # Accuracy rate
glmt["Yes","1"]/sum(glmt["Yes",]) # True positive rate (sensitivity)
glmt["No","0"]/sum(glmt["No",])   # True negative rate (specificity)
glmt["No","1"]/sum(glmt["No",])   # False positive rate
glmt["Yes","0"]/sum(glmt["Yes",]) # False negative rate
glmt["Yes","1"]/sum(glmt[,"1"])   # Positive predictive value (precision)
glmt["No","1"]/sum(glmt[,"1"])    # False discovery rate
#summary(glm(HeartDisease~.-PhysicalActivity,family=binomial,data=train)) # Manual backward selection
#summary(glm(HeartDisease~.-PhysicalActivity-Diabetic,family=binomial,data=train))
#summary(glm(HeartDisease~.-PhysicalActivity-Diabetic-Race,family=binomial,data=train))
#summary(glm(HeartDisease~.-PhysicalActivity-Diabetic-Race-AgeCategory,family=binomial,data=train))
#summary(glm(HeartDisease~.-PhysicalActivity-Diabetic-Race-AgeCategory-BMI,family=binomial,data=train))
summary(glm(HeartDisease~.-PhysicalActivity-Diabetic-Race-AgeCategory-BMI,family=binomial,data=train))$aic
table(test$HeartDisease,round(predict(glm(HeartDisease~.-PhysicalActivity-Diabetic-Race-AgeCategory-BMI,family=binomial,data=train),test,type="response")))
```