---
title: "STAT 488 Paper 2: \"Changes in the Type of Sports Activity Due to COVID-19: Hypochondriasis and the Intention of Continuous Participation in Sports\""
author: "Charles Hwang"
date: "4/24/2022"
output: pdf_document
header-includes: \usepackage{setspace}\doublespacing
---
## Introduction

The article I chose is titled "Changes in the Type of Sports Activity Due to COVID-19: Hypochondriasis and the Intention of Continuous Participation in Sports". Written by Chulhwan Choi and Chul-Ho Bum, this paper studied the extent of hypochondriasis (a condition described as being unduly worried about having a serious disease) among those who continuously performed physical activity in Seoul, South Korea during the onset of the COVID-19 pandemic. The study reviewed the intangible benefits of physical activity like building one's immune system, pleasure, joy, satisfaction, and stress and anxiety relief and how they may prevent or limit the effects of psychological symptoms like hypochondriasis (also known as illness anxiety disorder or IAD).

The personal "cost-benefit" analyses that those in the study took during the onset of the pandemic was also examined. For example, some participants who participated in group exercises prior to the pandemic modified their routine to individual exercises to limit contact with others, which could be a personal belief that the potential consequences of contracting disease outweighed the various benefits of exercise. Some participants also reduced the frequency of their exercise or began abstaining from exercise altogether. The authors intend for their study to be used in future pandemics, writing: "The present study is considered to be an important research attempt that analyzes and predicts the behavior of people not only in COVID-19 but also future pandemics because of the continuous outbreaks of respiratory syndromes."

## Statistical Methods Employed

A total of 229 responses[^2] collected from March 10 through April 6, 2020 were used in the study, with variables consisting of age group (young, middle-aged, or older), gender (female or male), type of sport/exercise (individual or group), most common sport/exercise[^1], frequency of sport/exercise (always, very often, often, sometimes, or rarely), and ratings of several statements on a five-point Likert scale (<https://en.wikipedia.org/wiki/Likert_scale>) between "strongly disagree" (1 point) and "strongly agree" (5 points).

In analyzing whether there was sufficient evidence of hypochondriasis, which served as the main source of dependent variables, four categories were used: (1) thanatophobia (disproportionate fear of death), (2) worry about illness, (3) disease phobia (nosophobia), and (4) symptom preoccupation (somatic symptom disorder). An additional dependent variable, (5) intention of continuing to exercise in the future (or as the paper calls it, "intention of continuous participation"), was also used.

Exploratory **factor analysis** was performed with $m=4$ and a Varimax rotation showed the following 12 statements had the most significant components:

1. I fear when I hear news that reminds me of death.
2. Thinking about death makes me feel afraid.
3. I fear that I might die.
4. I worry about health.
5. I worry about becoming seriously ill in the future.
6. I am scared when I think about serious diseases.
7. I fear that I may contract COVID-19.
8. I fear that I may become seriously ill.
9. When I read an article about virus, I feel similar symptoms.
10. When a symptom persists, I believe I have a serious illness.
11. If I detect a symptom, I can't think anything else because of it.
12. If I feel unusual symptoms in my body, I worry about them.

Table 2 in the study shows that each of the four categories corresponds to a factor, with a group of three components clearly the most important in each factor. From reading the statements, this makes sense intuitively and each statement relatively matches the definitions of its factor's corresponding category.

Multivariate analyses of variance (**MANOVA**) were performed on age, type of sport, and the interaction between the two. **Assumptions** of random and independent observations, multivariate normality of dependent variables, and equality of covariance matrices were made and the following **hypotheses** were used (where $\mu$ is referring to the $p\times1$ mean matrix):

1. $H_0:\mu_Y=\mu_M=\mu_O$ (Age)

    $H_A:$ At least one $\mu_i$ is different

2. $H_0:\mu_I=\mu_G$ (Type of sport)

    $H_A:\mu_I\neq\mu_G$

3. $H_0:\mu_{YI}=\mu_{YG}=\mu_{MI}=\mu_{MG}=\mu_{OI}=\mu_{OG}$ (Interaction)

    $H_A:$ At least one $\mu_{ij}$ is different

The effect of age was statistically significant on all independent variables except symptom preoccupation ($F=0.490$, $p=0.6132844$) at the $\alpha=0.05$ level, using 2 and 223 degrees of freedom (Table 3). Post-hoc analysis shows that all three age groups were different for intention of continuing exercise, the young age group was different than the other two for worry about illness[^3] and disease phobia, and the older age group was different than the other two for thanatophobia (Table 4). The effect of type of sport was statistically significant on all independent variables[^4] except thanatophobia ($F=0.159$, $p=0.6904604$) at the $\alpha=0.05$ level, using 1 and 223 degrees of freedom (Table 5). The effect of the interaction between age and type of sport was statistically significant on thanatophobia and disease phobia at the $\alpha=0.05$ level, using 2 and 223 degrees of freedom (Table 6). The interaction plots (Figures 1 and 2) confirm this significance.

## Critique of Statistical Methods

One of the things I noticed was the 12 statements in the questionnaire **did not necessarily indicate** that hypochondriasis was present. For example, given the time period of the study, affirmative responses to statements 1 through 8 could simply indicate a natural reaction and an increased focus on one's health rather than an irrational or unwarranted fear of serious disease. The SARS‑CoV‑2 virus is novel (new), meaning there was little available research on the severity, transmissibility, and symptoms from resulting disease, and the uncertainty and lack of information could have provoked a stronger emotional reaction that usual. There has also historically been an increased societal and cultural importance on physical health and well-being in East Asian countries which could have further confounded results of increased hypochondriasis.

As someone who frequently takes online surveys[^5], the specific wording of a question or statement is very important and the inclusion or omission of even a single word can yield significantly different results. Inherent human bias can subconsciously include or exclude certain information or present a question in a biased manner causing participants to be inclined to answer a certain way. The translation of the statements from Korean to English in the paper may also contribute to wording that is not completely accurate and representative of the original statement but conveys the general meaning.

Another main thing I saw was that the full questionnaire used in the **data collection was not provided**, and thus several variables or statements could have been excluded from the analysis without the readers' knowledge. The authors never provide any specific justification for using four categories or those specific categories, only writing that they "are appropriate to analyze hypochondriasis in COVID-19." They also never define the specific differences between the groups to the reader, which can be confusing if unfamiliar with the subject matter. The survey methods are cited and referenced, but the number of statements (or the specific statements not listed) in the survey was never disclosed which led to some confusion. The authors do acknowledge the randomness and independence assumptions may have been violated, writing: "... this study used convenience sampling to draw the samples, which can lead to certain restrictions in obtaining representativeness in research. Accordingly, it is necessary to take account of various sampling methods that use probabilistic sampling in further research. Moreover, with sport participants rapidly decreasing in number due to the spread of COVID-19, there were many difficulties in securing research participants for this study."

Lastly, the purpose of the study was a bit unclear initially, with the 1.1 Introduction section conflating benefits of physical health and exercise with increase in hypochondriasis. The assumptions, hypotheses, and test statistics for post-hoc analysis (Table 4) were also never explicitly stated. There did not appear to be any major spelling or grammar errors, but the typos in the results could have been a result of insufficient proofreading and review of the paper prior to publication.

## Conclusion

I believe this is a good study given the constraints in place during data collection. Some improvement could be made with reporting accurate results and disclosing additional statistical information to the reader. Although the study was done just two years ago as opposed to some older studies, the multivariate concepts were relatively basic and easy to understand. I would be interested to see how much support or resources were provided for the study because it appears it was done entirely by the two authors, who appear to be one graduate and one undergraduate student. Overall, this was a good use of multivariate concepts like factor analysis and MANOVA.

[^1]: There were ten total exercises listed. Five (home training, walking, running, tracking, cycling) were considered individual exercises and five (golf, gym, basketball, baseball, swimming) were considered group exercises.

[^2]: 231 total responses were collected out of 300 questionnaires distributed for a 77% response rate and two "incomplete or insincere responses" were excluded.

[^3]: It appears the *p*-value between older (G3) and middle-aged (G2) for worry about illness is listed incorrectly as 0.000. Looking at the reflexive p-value between middle-aged (G2) and older (G3) and reading the analysis, the correct *p*-value should be approximately 0.454.

[^4]: It appears the *p*-value for symptom preoccupation is listed incorrectly as 1.000. Since the information provided shows the *F*-statistic as *F*(1, 223) = 12.680, the correct *p*-value should be approximately `r format(1-pf(12.680,1,223),scientific=FALSE)`.

[^5]: https://account.yougov.com/us-en/join?referral=Q7UP6Nq1O6tVWDPId5ut2Q

## Works Cited

| Choi, Chulhwan, and Chul-Ho Bum. "Changes in the Type of Sports Activity Due to COVID-19:
|         Hypochondriasis and the Intention of Continuous Participation in Sports." International Journal of
|         Environmental Research and Public Health. 2020; vol. 17, no. 13: 4871,
|         <https://doi.org/10.3390/ijerph17134871>.