---
title: "Homework 1"
author: "Charles Hwang"
date: "1/18/2022"
output: pdf_document
---
Charles Hwang

Dr. Perry

STAT 451-001

18 January 2022

## Problem 1
```{r Problem 1}
rm(list=ls())
update.packages(repos="https://cran.r-project.org")
```

## Problem 2
```{r Problem 2}
Skill<-c(rep("Expert",9), rep("Average",9))                             # Problem 2(a)
Hand<-rep(c(rep("Bad",3),rep("Neutral",3),rep("Good",3)),2)
Balance<-c(4.00,8.52,6.55,11.99,6.65,7.64,11.29,9.12,22.45,3.58,4.45,8.74,11.86,9.19,13.49,16.33,0.45,19.24)
df.poker<-data.frame(Skill,Hand,Balance)                                # Problem 2(b)
data.frame(mean(df.poker$Balance),sd(df.poker$Balance))                 # Problem 2(c)
boxplot(Balance~Skill,main="Poker Balance by Skill Level",horizontal=T) # Problem 2(d)
meanBalE<-mean(df.poker$Balance[df.poker$Skill=="Expert"])              # Problem 2(e)
meanBalA<-mean(df.poker$Balance[df.poker$Skill=="Average"])
sdBalE<-sd(df.poker$Balance[df.poker$Skill=="Expert"])
sdBalA<-sd(df.poker$Balance[df.poker$Skill=="Average"])
data.frame(meanBalE,sdBalE,meanBalA,sdBalA)
t.test(Balance~Skill)                                                   # Problem 2(f)
```

## Problem 3
```{r Problem 3}
depression<-read.table("/Users/newuser/Desktop/Notes/Graduate/STAT 451 - Nonparametric Statistical Methods/depression.txt",header=TRUE,sep="") # Problem 3(a)
head(depression)                                 # Problem 3(b)
plot(depression$y~depression$age,main="Problem 3(c) - Plot of Depression Score vs. Age",xlab="Age",ylab="Score")
plot(depression$y[depression$TRT=="A"]~depression$age[depression$TRT=="A"],main="Problem 3(d) - Plot of Depression Score vs. Age, Treatment A",xlab="Age",ylab="Score")
plot(depression$y~depression$age,col=ifelse(depression$TRT=="A","blue",ifelse(depression$TRT=="B","red","black")),pch=19,main="Problem 3(e) - Plot of Depression Score vs. Age by Treatment",xlab="Age",ylab="Score")
fit.depression<-aov(depression$y~depression$TRT) # Problem 3(f)
# H_0: The mean depression scores for each treatment type are the same
# H_A: At least one mean depression score is different
summary(fit.depression)
# We reject H_0 at the alpha = 0.05 level. There is sufficient evidence (p = 0.04453905)
# that at least one of the mean depression scores is different.
set.seed(1801)                                   # Problem 3(g)
ysamp<-sample(depression$y,8,replace=TRUE)
ysamp
ysampmat<-matrix(0,8,3)                          # Problem 3(h)
for (i in 1:3){ysampmat[,i]=sample(depression$y,8,replace=T)}
ysampmat
```

## Problem 4
```{r Problem 4}
install.packages("binom",repos="https://cran.r-project.org") # Problem 4(a)
library("binom")
binom.confint(x=7,n=20,conf.level=0.95,method="all")
# We are 95 percent confident that the binomial probability of having x = 7 successes in
# n = 20 attempts using the prop.test method is between 0.1630867 and 0.5905104.
install.packages("pwr",repos="https://cran.r-project.org")   # Problem 4(b)
library("pwr")
pwr.t.test(d=abs(45-48)/2.3,n=10,sig.level=0.05,type="one.sample",alternative="two.sided")
```

We can see the power for this test is `r pwr.t.test(d=abs(45-48)/2.3,n=10,sig.level=0.05,type="one.sample",alternative="two.sided")$power`.