---
title: "Hwang_Hw5"
author: "Charles Hwang"
date: "11/26/2021"
output: pdf_document
---
## Problem 8.2

```{r Problem 8.2}
rm(list=ls())
A<-as.factor(rep(c(-1,1),4))
B<-as.factor(rep(c(-1,1),2,each=2))
C<-as.factor(rep(c(-1,1),each=4))
D<-as.factor(as.numeric(as.character(A))*as.numeric(as.character(B))*as.numeric(as.character(C)))
length<-c(7.037,16.867,13.876,17.273,11.846,4.368,9.36,15.653) # (1), ad, bd, ab, cd, ac, bc, abcd
l<-lm(length~A*B*C*D)
anova(l)
qq<-qqnorm(abs(l$effects[-1]),type="n") # Remove variables
text(qq$x,qq$y,labels=names(abs(l$effects[-1])))
abline(h=3.5) # Arbitrary cutoff
m<-lm(length~A+B+C+D+A*C) # New model
anova(m)
par(mfrow=c(1,3))
plot.design(data.frame(A,B,C,D,length))
interaction.plot(A,C,length,ylab="")
interaction.plot(C,A,length,ylab="")
# The interaction plots indicate there is interaction between pouring temperature (A)
# and heat treatment method (C). However, the ANOVA output shows the interaction is
# not significant at the alpha = 0.05 level (p = 0.11295). Because of this discrepancy,
# we should still proceed in creating and running a reduced model without the interaction
n<-lm(length~A+B+C+D)      # term to see the differences in ANOVA output and results.
anova(n)
shapiro.test(n$residuals)
bartlett.test(n$residuals~A)
bartlett.test(n$residuals~B)
bartlett.test(n$residuals~C)
bartlett.test(n$residuals~D)
# None of the null hypotheses were rejected, so the normality and
par(mfrow=c(1,2))  # equal variance assumptions appear to be met.
qqnorm(n$residuals)
qqline(n$residuals)
plot(n$fitted.values,n$residuals)
abline(h=0)
# There appears to be some variation in the Q-Q plot. However, it is hard to accurately
# analyze and interpret the plots due to the small sample size.
```

## Problem 8.15
```{r Problem 8.15}
rm(list=ls()) # See Example 8.2 on pages 327-330
A<-as.factor(rep(c(-1,1),8))
B<-as.factor(rep(c(-1,1),4,each=2))
C<-as.factor(rep(c(-1,1),2,each=4))
D<-as.factor(rep(c(-1,1),each=8))
E<-as.factor(as.numeric(as.character(A))*as.numeric(as.character(B))*as.numeric(as.character(C))*as.numeric(as.character(D)))
y<-c(8,9,34,52,16,22,45,60,8,10,30,50,15,21,44,63) # e, a, b, abe, c, ace, bce, abc, d,
s<-lm(y~A*B*C*D*E)                               # ade, bde, abd, cde, acd, bcd, abcde
anova(s)
qq<-qqnorm(abs(s$effects[-1]),type="n") # Remove variables
text(qq$x,qq$y,labels=names(abs(s$effects[-1])))
abline(h=9) # Arbitrary cutoff
t<-lm(y~A*B+C) # New model
anova(t)
par(mfrow=c(1,3))
plot.design(data.frame(A,B,C,y))
interaction.plot(A,B,y,ylab="")
interaction.plot(B,A,y,ylab="")
# There appears to be some interaction between aperture setting (A) and exposure time (B).
# This could mean the two factors are related or associated with each other.
shapiro.test(t$residuals)
bartlett.test(t$residuals~A)
bartlett.test(t$residuals~B)
bartlett.test(t$residuals~C)
# We should exercise some caution here as the null hypothesis of the Shapiro-Wilk test is
# close to being rejected at the alpha = 0.05 level (p = 0.07919). The assumption of
par(mfrow=c(1,2))                               # normality may be slightly violated.
qqnorm(t$residuals)
qqline(t$residuals)
plot(t$fitted.values,t$residuals)
abline(h=0)
# There is a slight variation in the Q-Q plot.
```

# Problem 13.2
(a)
```{r Problem 13.2(a)}
rm(list=ls())
part<-as.factor(rep(1:10,each=9))
ins<-as.factor(rep(1:3,10,each=3))
ti<-c(37,38,37,41,41,40,41,42,41,42,41,43,42,42,42,43,42,43,30,31,31,31,31,31,29,30,28,42,43,42,43,43,43,42,42,42,28,30,29,29,30,29,31,29,29,42,42,43,45,45,45,44,46,45,25,26,27,28,28,30,29,27,27,40,40,40,43,42,42,43,43,41,25,25,25,27,29,28,26,26,26,35,34,34,35,35,34,35,34,35)
c<-lm(ti~part*ins)
anova(c)
```

We can see the p-value for the interaction term is significant at the $\alpha$ = 0.05 level (p < 0.000001).

(b)
```{r Problem 13.2(b), message=FALSE}
MSA<-anova(c)[1,3]
MSB<-anova(c)[2,3]
MSAB<-anova(c)[3,3]
MSE<-anova(c)[4,3]
a<-nlevels(part)
b<-nlevels(ins)
n<-length(ti)/a/b
fp<-data.frame(c(MSA/MSAB,1-pf(MSA/MSAB,a-1,(a-1)*(b-1))),c(MSB/MSAB,1-pf(MSB/MSAB,b-1,(a-1)*(b-1))),c(MSAB/MSE,1-pf(MSAB/MSE,(a-1)*(b-1),a*b*(n-1))))
names(fp)<-c("A","B","AB")
row.names(fp)<-(c("F","p"))
fp["F",]<-format(fp["F",],scientific=FALSE)
fp
est<-data.frame(c(MSE),c((MSA-MSE)/(b*n)),c((MSB-MSE)/(a*n)),c((MSAB-MSE)/n),c(MSE+(MSB-MSE)/(a*n)))
names(est)<-c("sigma^2","sigma^2_tau","sigma^2_beta","sigma^2_taubeta","sigma^2_gauge")
row.names(est)<-("Estimate")
est
shapiro.test(c$residuals)
bartlett.test(c$residuals~part)
bartlett.test(c$residuals~ins)
library(car)
leveneTest(c)
# We should exercise caution here as the null hypothesis for the Shapiro-Wilk test has
# been rejected (p = 0.0035) and the assumption of normality may be violated.
par(mfrow=c(1,2))
qqnorm(c$residuals)
qqline(c$residuals)
plot(c$fitted.values,c$residuals)
abline(h=0)
# There is some variation in the residuals vs. fitted values plot.
```

(c)
```{r Problem 13.2(c)}
rm(list=ls()) # https://sakai.luc.edu/portal/directtool/3f2340da-9af7-4db6-8c07-3e89c943e075
```

# Problem 13.5
```{r Problem 13.5}
temp<-as.factor(rep(c(800,825,850),times=6))
pos<-as.factor(rep(1:2,each=9))
density<-c(570,1063,565,565,1080,510,583,1043,590,528,988,526,547,1026,538,521,1004,532)
d<-lm(density~temp*pos)
anova(d)
MSA<-anova(d)[1,3] # We can see the p-value for the interaction term is not
MSB<-anova(d)[2,3] # significant at the alpha = 0.05 level (p = 0.42711).
MSAB<-anova(d)[3,3]
MSE<-anova(d)[4,3]
a<-nlevels(temp)
n<-length(density)/a/nlevels(pos)
fpA<-data.frame(c(MSA/MSAB),c(1-pf(MSA/MSAB,anova(d)[1,1],anova(d)[3,1])))
names(fpA)<-c("F","p")
row.names(fpA)<-("A")
fpA
est<-data.frame(c((MSB-MSE)/(a*n)),c((MSAB-MSE)/n))
names(est)<-c("sigma^2_beta","sigma^2_taubeta")
row.names(est)<-("Estimate")
est # Page 576 provides an example with a negative estimate for sigma^2_taubeta.
e<-lm(density~temp+pos) # Reduced model without interaction term
anova(e)
cat("Reduced model estimate of sigma^2_beta:",(anova(e)[2,3]-anova(e)[3,3])/(a*n),"\n")
# We can see this estimate for sigma^2_beta is very similar to the one in the original model.
shapiro.test(e$residuals)
bartlett.test(e$residuals~temp)
bartlett.test(e$residuals~pos)
# We should exercise some caution here as the null hypothesis of the Shapiro-Wilk test is
# close to being rejected at the alpha = 0.05 level (p = 0.09529). The assumption of
par(mfrow=c(1,2))                               # normality may be slightly violated.
qqnorm(e$residuals)
qqline(e$residuals)
plot(e$fitted.values,e$residuals)
abline(h=0)
# There is a slight variation in the Q-Q plot.
```