---
title: "Homework 5"
author: "Charles Hwang"
date: "6/30/2022"
output: pdf_document
---
Charles Hwang

Dr. Matthews

STAT 488-001

30 June 2022

## Problem 10.3

### Problem 10.3(a)

```{r Problem 10.3(a)}
rm(list=ls())
set.seed(306)
p1<-rbeta(1000,6,10-6)
p2<-rbeta(1000,10,20-10)
quantile(p1-p2,c(0.05/2,1-0.05/2))
hist(p1-p2,breaks=20,main="Problem 10.3(a) - Histogram of 1,000 Draws from p_1-p_2")
abline(v=0,col="red")
abline(v=quantile(p1-p2,c(0.05/2,1-0.05/2)),lty=2)
mean(p1>p2)
```

### Problem 10.3(b)

```{r Problem 10.3(b)}
pd<-\(x) x^(7-1)*(1-x)^(5-1)/beta(7,5)-x^(11-1)*(1-x)^(11-1)/beta(11,11)
x<-c(seq(0,0.232165,0.0001),seq(0.5856,1,0.0001)) # Finding points via Desmos
plot(pd,main="Problem 10.3(b) - Plot of Beta(7,5)-Beta(11,11)")
polygon(x,c(0,pd(seq(0,1,0.0001))[pd(seq(0,1,0.0001))>=0]),col="orange")
points(c(0,0.232165,0.58564,1),rep(0,4),col="red") # Intersection points with x-axis
length(x)/length(seq(0,1,0.0001)) # Length of [0,1] for which the function is positive
0.58564/0.232165*(integrate(pd,0,0.232165)$value+integrate(pd,0.58564,1)$value) # C * E[f(x)]
```

## Problem 2.

```{r Problem 2.}
y<-c(144.8,113.2,82.6,46.1,117.6)
mean(y)           # mean = alpha / beta
var(y)        # variance = alpha / beta^2
b<-mean(y)/var(y) # beta = mean / variance
a<-b*mean(y)     # alpha = beta * mean
Xm<-Ym<-rep(NA,500)
mpd<-function(X,Y){a<-exp(Y)*exp(X)/(exp(X)+1)
  b<-exp(Y)/(exp(X)+1)
  exp(-1845+log(a)/2+log(b+1)+sum(a*log(b)-(y+a)*log(b+1)+lgamma(y)-lbeta(a,y))+2*Y+X-2*log(exp(X)+1))}
X<-seq(4.2,5,length=50) # Setting bounds of contour plot via trial-and-error
Y<-seq(1.5,4.5,length=50)
z<-matrix(NA,length(Y),length(X))
for (i in 1:length(Y)){for (j in 1:length(X)){z[j,i]<-mpd(X[j],Y[i])}}
par(mfrow=c(1,2))
contour(X,Y,z,xlab="ln(alpha / beta)",ylab="ln(alpha + beta)",main="Problem 2. - Contour Plot")
points(log(a/b),log(a+b),pch=19) # The original estimate appears to be a bit off.
set.seed(306)
for (k in 1:length(Xm)){Xm[k]<-sample(X,1,TRUE,apply(z,1,sum)/sum(apply(z,1,sum)))
  Ym[k]<-sample(Y,1,TRUE,z[which(Xm[k]==X),]/sum(z[which(Xm[k]==X),]))}
contour(X,Y,z,xlab="ln(alpha / beta)",ylab="ln(alpha + beta)",main="Draws from Marginal Posterior")
Xm<-Xm+runif(length(Xm),-diff(X)/2,diff(X)/2)
Ym<-Ym+runif(length(Ym),-diff(Y)/2,diff(Y)/2)
points(Xm,Ym)
points(mean(Xm),mean(Ym),pch=19,col="red")
alpha<-exp(Ym)*(exp(Xm)/(exp(Xm)+1))
beta<-exp(Ym)/(exp(Xm)+1)
quantile(alpha,c(0.05/2,1-0.05/2))      # 95 percent credible interval of alpha
a       # We can see this interval contains our original estimate of alpha.
quantile(beta,c(0.05/2,1-0.05/2))       # 95 percent credible interval of beta
b       # We can see this interval contains our original estimate of beta.
quantile(alpha/beta,c(0.05/2,1-0.05/2)) # 95 percent credible interval of y
sort(y)
# We can see this interval contains the middle three values of y. It is reasonable
# that the minimum and maximum values are not included as they appear to be outliers.
```