---
title: "Homework 2"
author: "Charles Hwang"
date: "6/14/2022"
output: pdf_document
---
Charles Hwang

Dr. Matthews

STAT 488-001

14 June 2022

## Problem 3.3

### Problem 3.3(b)

```{r Problem 3.3(b)}
rm(list=ls())
set.seed(1406)
c<-1.013+0.24/sqrt(32)*rt(1000,32-1)
t<-1.173+0.20/sqrt(36)*rt(1000,36-1)
hist(t-c,breaks=seq(-0.1,0.4,0.025))
quantile(t-c,c(0.05/2,1-0.05/2))
```

## Problem 3.4

### Problem 3.4(a)

```{r Problem 3.4(a)}
library(ggplot2)
library(metR)
p0<-p1<-seq(0,1,0.001)
p0p1<-expand.grid(p0,p1)
zim<-function(p0,p1){return(p0^38.5*(1-p0)^634.5*p1^21.5*(1-p1)^657.5)}
z<-vector(mode="numeric",length=nrow(p0p1))
for(i in 1:nrow(p0p1)){z[i]<-zim(p0p1[i,"Var1"],p0p1[i,"Var2"])}
contour(p0,p1,matrix(z,1001,1001),xlim=c(0.041,0.075),ylim=c(0.021,0.046),xlab="p0",ylab="p1",main="Problem 3.4(a) - Contour Plot with MLE")
points(39/(674-39),22/(680-22))
set.seed(1406)
x<-rbeta(1000,39.5,635.5)
y<-rbeta(1000,22.5,658.5)
contour(p0,p1,matrix(z,1001,1001),xlim=c(0.034,0.092),ylim=c(0.016,0.056),xlab="p0",ylab="p1",main="Problem 3.4(a) - Contour Plot with 1,000 Simulations")
points(x,y,cex=.6)
```

### Problem 3.4(b)

```{r Problem 3.4(b)}
OR<-function(p0,p1){return(p1/(1-p1)/(p0/(1-p0)))}
pOR<-apply(data.frame(p0=x,p1=y),1,function(row) OR(row[1],row[2]))
hist(pOR,xlab="Odds Ratio (OR)",main="Problem 3.4(b) - Posterior Distribution of Odds Ratio")
abline(v=1)
summary(pOR)
```

We can see the distribution is right-skew with a mean of `r mean(pOR)`.

### Problem 3.6(b)

```{r Problem 3.6(b)}
w<-c(53,57,66,67,72)
b<-function(N,w){return(prod(sapply(w,function(x) choose(N,x)/N))*beta(sum(w)+1,5*N-sum(w)+1))}
N<-seq(63,264,1) # Testing different bounds
y<-sapply(N,function(x) b(x,w))
plot(N,y,type="l",main="Problem 3.6(b) - Marginal Posterior of N")
polygon(N[N>=100],c(0,y[(100-min(N)+1+1):length(y)]),col="orange")
sum(y[(N>100)])/sum(y)
```